name          'kietsy-tinc'
version       '0.1.0'
source        'https://github.com/kietsy/kietsy-tinc'
author        'Danny Arnold'
license       'Apache 2.0'
summary       'Puppet module for tinc'
description   'Puppet module for tinc'
project_page  'https://github.com/kietsy/kietsy-tinc'

dependency 'puppetlabs/stdlib'
